addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")
addSbtPlugin("org.scoverage" % "sbt-coveralls" % "1.1.0")
addSbtPlugin("org.foundweekends" % "sbt-bintray" % "0.5.1")
addSbtPlugin("ch.epfl.scala" % "sbt-release-early" % "1.1.0" exclude("ch.epfl.sala", "sbt-bintray"))
addSbtPlugin("com.dwijnand" % "sbt-travisci" % "1.1.1")
